apiVersion: v2
name: platform
version: 1.1.0
description: Unified Helm chart for Trading + Monitoring Stack
dependencies:
  - name: trading
    version: 1.0.0
    repository: "file://../trading"
  - name: prometheus
    version: 1.0.0
    repository: "file://../prometheus"
  - name: grafana
    version: 1.0.0
    repository: "file://../grafana"
  - name: loki
    version: 1.0.0
    repository: "file://../loki"
  - name: promtail
    version: 1.0.0
    repository: "file://../promtail"
