trading:
  enabled: false

prometheus:
  server:
    service:
      type: NodePort
      nodePort: 30900
    nodeSelector:
      role: monitor

grafana:
  service:
    type: NodePort
    nodePort: 30300
  adminUser: admin
  adminPassword: admin
  nodeSelector:
    role: monitor

loki:
  grafana:
    enabled: false
  prometheus:
    enabled: false
  loki:
    auth_enabled: false
    storage:
      type: filesystem
  nodeSelector:
    role: monitor

promtail:
  config:
    lokiAddress: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
