apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-signal
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate-signal
  template:
    metadata:
      labels:
        app: generate-signal
    spec:

      containers:
        - name: generate-signal
          image: 173381466759.dkr.ecr.ap-northeast-1.amazonaws.com/quant:latest
          imagePullPolicy: IfNotPresent
          command: [ "python", "-u", "-m", "trade_binance.q_get_symbol_future_p" ]
          ports:

            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: REDIS_HOST
              value: "service-r"
            - name: REDIS_PORT
              value: "6379"
            - name: WS_HOST
              value: "service-a"
            - name: WS_PORT
              value: "8765"

          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: efs-storage
              mountPath: /mnt/efs
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-claim