apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-data
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-data
  template:
    metadata:
      labels:
        app: fetch-data
    spec:
      containers:
        - name: fetch-data
          image: 173381466759.dkr.ecr.ap-northeast-1.amazonaws.com/quant:latest
          # for manual pull image
          imagePullPolicy: IfNotPresent

          command: ["python", "-u", "-m", "ws.ws_binance_kline_future"]
          ports:
            - containerPort: 8765
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config

          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: efs-storage
              mountPath: /mnt/efs
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0

      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-claim


---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: fetch-data
  ports:
    - port: 8765
      targetPort: 8765
  type: ClusterIP