apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade
  template:
    metadata:
      labels:
        app: trade
    spec:

      containers:
        - name: trade
          image: 173381466759.dkr.ecr.ap-northeast-1.amazonaws.com/quant:latest
          imagePullPolicy: IfNotPresent
          command: [ "python", "-u", "-m", "trade_binance.q_trade_future_binance_p" ]

          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: REDIS_HOST
              value: "service-r"
            - name: REDIS_PORT
              value: "6379"

          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: efs-storage
              mountPath: /mnt/efs
          securityContext:
            runAsUser: 0
            runAsGroup: 0

      securityContext:
        fsGroup: 0
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-claim
