apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.efs.storageClass }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efs.fileSystemId }}
  directoryPerms: "700"
reclaimPolicy: {{ .Values.efs.reclaimPolicy }}
volumeBindingMode: Immediate
mountOptions:
  - tls

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.efs.accessMode  }}
  storageClassName: {{ .Values.efs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.efs.size  }}
