apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.efs.storageClass | default "efs-sc" }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efs.fileSystemId }}
  directoryPerms: "700"
reclaimPolicy: {{ .Values.efs.reclaimPolicy | default "Retain" }}
volumeBindingMode: Immediate
mountOptions:
  - tls

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.efs.claimName | default "efs-claim" }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.efs.accessMode | default "ReadWriteMany" }}
  storageClassName: {{ .Values.efs.storageClass | default "efs-sc" }}
  resources:
    requests:
      storage: {{ .Values.efs.size | default "100Mi" }}
