apiVersion: v2
name: trading
description: A Helm chart to deploy trading microservices (signal, data, redis) on EKS
type: application
version: 1.0.0
appVersion: "1.0.0"


keywords:
  - kubernetes
  - helm
  - trading
  - microservices
  - aws
  - eks

